### ISSUE TITLE
Can't find TimeTables

### ISSUE THREAD

**Issue by feja111** [Sematre/TG-API#2]
![image](https://user-images.githubusercontent.com/64980644/97721094-50b94580-1ac9-11eb-97c2-cd22ae3024c3.png)

**Comment by Sematre** [comment]
Hey, thank you for your interest in this project.
Please note that this project is intended to be used at the **Gewerbliche Schule Ravensburg**.
It's **not** intended to be used at other schools or universities, nor is it planned to support them in the near future.

If you need some sort of API for DSBmobile you might be interested in my other project [DSBmobile-API](https://github.com/Sematre/DSBmobile-API).
